version: '3'

services:
  php:
    image: php:8.0-fpm
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html

  nginx:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
